CREATE TABLE USER (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) COLLATE utf8_bin DEFAULT NULL COMMENT '名称',
    `department_id` INT(11) DEFAULT NULL,
    `create_time` DATE DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`)
) ENGINE= INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
CREATE TABLE `department` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) COLLATE utf8_bin DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=utf8_bin;